[[heading]]
# 1. Introduction
level = 1
greedy = true
font.name = "XCharter-Bold"
font.size = 12.951399803161621
# font.size_tolerance = 1e-5
# font.color = -0x1000000
# font.superscript = false
# font.italic = false
# font.serif = true
# font.monospace = false
# font.bold = true
# bbox.left = 62.36199951171875
# bbox.top = 442.4657897949219
# bbox.right = 154.67959594726562
# bbox.bottom = 455.41717529296875
# bbox.tolerance = 1e-5
[[heading]]
# 3. Methodology
level = 1
greedy = true
font.name = "XCharter-Bold"
font.size = 12.951399803161621
# font.size_tolerance = 1e-5
# font.color = -0x1000000
# font.superscript = false
# font.italic = false
# font.serif = true
# font.monospace = false
# font.bold = true
# bbox.left = 62.36199951171875
# bbox.top = 610.2027587890625
# bbox.right = 158.4484405517578
# bbox.bottom = 623.1541748046875
# bbox.tolerance = 1e-5
[[heading]]
# 4. Experiments
level = 1
greedy = true
font.name = "XCharter-Bold"
font.size = 12.951399803161621
# font.size_tolerance = 1e-5
# font.color = -0x1000000
# font.superscript = false
# font.italic = false
# font.serif = true
# font.monospace = false
# font.bold = true
# bbox.left = 62.36198425292969
# bbox.top = 376.009765625
# bbox.right = 155.14581298828125
# bbox.bottom = 388.9611511230469
# bbox.tolerance = 1e-5